# Generated by Django 2.1.7 on 2019-02-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=255, upload_to='coins', verbose_name='Изображение')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Номинал')),
            ],
            options={
                'verbose_name': 'монеты',
                'verbose_name_plural': 'монеты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('summ', models.PositiveIntegerField(verbose_name='Сумма')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Количество')),
                ('sort', models.PositiveSmallIntegerField(verbose_name='Номинал')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
            },
        ),
        migrations.CreateModel(
            name='UserCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'деньги покупателя',
                'verbose_name_plural': 'деньги покупателя',
            },
        ),
        migrations.CreateModel(
            name='VMCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'деньги машины',
                'verbose_name_plural': 'деньги машины',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='Товар'),
        ),
    ]
