# Generated by Django 2.1.7 on 2019-02-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVMCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Coin', verbose_name='Монета')),
            ],
            options={
                'verbose_name': 'активные деньги',
                'verbose_name_plural': 'активные деньги',
            },
        ),
    ]
