# Generated by Django 2.1.7 on 2019-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_uservmcash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='img',
        ),
        migrations.AddField(
            model_name='coin',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Рубль'),
            preserve_default=False,
        ),
    ]
