# Generated by Django 2.1.7 on 2019-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190214_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
