# Generated by Django 2.1.7 on 2019-02-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RenameField(
            model_name='usercash',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RenameField(
            model_name='uservmcash',
            old_name='count',
            new_name='cnt',
        ),
        migrations.RenameField(
            model_name='vmcash',
            old_name='count',
            new_name='cnt',
        ),
    ]
